spring:
  # import .env
  # .env를 .env.properties 로 해석
  # optional이 붙어서 .env파일이 없어도 에러나지 않음
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:tcp://localhost/~/bookforest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jwt:
    secret: ${JWT_SECRET_KEY}
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace


